# Data Analyst SmolAgents Demos Configuration

paths:
  smolagent_custom_tools: genai_tk.tools.smolagents
  ekg_data: 

  
smolagents_codeact:
  - name: "from Hugging Face"
    tools: 
      - class: smolagents:WebSearchTool
      - class: smolagents:VisitWebpageTool
      - langchain: 
    authorized_imports: ["pandas", "matplotlib.*", "sklearn.*"]
    examples:
      - "How many seconds would it take for a leopard at full speed to run through Pont des Arts?"
      - "If the US keeps its 2024 growth rate, how many years will it take for the GDP to double?"
      - "Which Dutch player scored an open-play goal in the 2022 Netherlands vs Argentina game in the men's FIFA World Cup?"

  - name: "Titanic"
    tools:
      - class: ${paths.smolagent_custom_tools}.dataframe_tools:DataFrameTool
        name: "titanic_data_reader"
        description: "Data related to the Titanic passengers"
        source_path: ${paths.project}/use_case_data/other/titanic.csv
        
      - class: smolagents:WebSearchTool
      - class: smolagents:VisitWebpageTool
    authorized_imports: ["pandas", "matplotlib.*", "sklearn.*"]
    examples:
      - "What is the proportion of female passengers that survived?"
      - "Were there any notable individuals or families aboard "
      - "Plot in a bar chat the proportion of male and female survivors"
      - "What was the survival rate of passengers on the Titanic?"
      - "Did the passenger class have an impact on survival rates?"
      - "What were the ticket fares and cabin locations for the passengers?"
      - "What are the demographics (age, gender, etc.) of the passengers on the Titanic?"
      - "What feature would you engineered to predict survival rate ? Build a predictive model, and report the F1 score on a test set"

  - name: "Stock Price"
    tools:
     - function: ${paths.smolagent_custom_tools}.yfinance_tools:get_stock_info
     - function: ${paths.smolagent_custom_tools}.yfinance_tools:get_historical_price
     - class: smolagents:WebSearchTool
     - class: smolagents:VisitWebpageTool
    authorized_imports: ["pandas", "matplotlib.*"]
    mcp: 
     # - yahoo-finance-mcp
    examples:
      - "What is the current price of Meta stock?"
      - "Show me the historical prices of Apple vs Microsoft stock over the past 6 months"

  # - name: "Geo"
  #   tools:
  #     - class: smolagents:WebSearchTool
  #     - class: smolagents:VisitWebpageTool
  #   authorized_imports: ["pandas", "matplotlib.*", "streamlit_folium"]
  #   examples:
  #     - "Display the map of Toulouse"
  #     - "Display a map of France with a population density (gathered from Internet) layer by region or department"

  - name: "MCP"
    mcp_servers: ["filesystem", "weather", "playwright"]
    authorized_imports: ["pandas", "matplotlib.*"]
    examples:
      - "What is the current wind force in Toulouse ? "
      - "List current directory"
      - "connect to atos.net site and get recent news"

  # - name: "Vizro"
  #   mcp_servers: ["vizro-mcp"]
  #   examples:
  #     - "Create a Vizro dashboard with one page, a scatter chart, and a filter."
  #     - "Load sample data from tool and Create a Vizro dashboard with one page, a scatter chart, and a filter based on it "

  - name: "DeepSearch"
    tools:
    #  - class: ${paths.smolagent_custom_tools}.browser_use:AsyncBrowserUseTool
      - class: ${paths.smolagent_custom_tools}.browser_use:BrowserUseTool

    examples:
      - "Search for the latest AI news and summarize the top 3 stories"
      - "Write a short story on GPT-5 models"

